/* SUPPRESSION DES TABLES */
/* La supression d'une table retire sa définition du dictionnaire de données
Tous les indexes et triggers associés sont également supprimés
Toutes les vues et procédures PL/SQL dépendant de la table supprimée deviennent invalides
Les synonymes créés sur la table persistent mais leur utilisation retourne une erreur
*/

DROP TABLE "SPECIALITE" CASCADE CONSTRAINTS;
DROP TABLE "MEDECIN" CASCADE CONSTRAINTS;
DROP TABLE "MALADE" CASCADE CONSTRAINTS;
DROP TABLE "TYPEVISITE" CASCADE CONSTRAINTS;
DROP TABLE "VISITE" CASCADE CONSTRAINTS;
DROP TABLE "VILLE" CASCADE CONSTRAINTS;
DROP TABLE "LOG_LMD" CASCADE CONSTRAINTS;
DROP TABLE "LOG_SYS" CASCADE CONSTRAINTS;

/* CREATION DE LA SEQUENCE POUR TABLE VILLE */

DROP SEQUENCE SEQ01;
CREATE SEQUENCE SEQ01 INCREMENT BY 1 START WITH 1;
-- SELECT SEQ01.nextval FROM dual;
-- SELECT SEQ01.currval FROM dual;

/* CREATION DES TABLES */

CREATE TABLE "VILLE" 
(	"ID_VILLE" NUMBER, 
	"NOM" VARCHAR2(25 BYTE) NOT NULL ENABLE,
  CONSTRAINT PK_VILLE PRIMARY KEY (ID_VILLE)
);

CREATE TABLE SPECIALITE 
( CODESPECIALITE CHAR(25 BYTE) NOT NULL ENABLE, 
	NOMSPECIALITE VARCHAR2(25 BYTE),
  CONSTRAINT PK_SPECIALITE PRIMARY KEY (CODESPECIALITE)
);

CREATE TABLE "MEDECIN" 
(	"NUMEROMED" VARCHAR(12) NOT NULL ENABLE, 
	"NOM" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"ADRESSE" CHAR(25 BYTE) NOT NULL ENABLE, 
	"CODEPOSTAL" NUMBER(5,0) NOT NULL ENABLE, 
	"VILLE" CHAR(25 BYTE) NOT NULL ENABLE, 
  "CODESPECIALITE" CHAR(25 BYTE) NOT NULL ENABLE, 
  "NBVISITES" NUMBER(5,0) DEFAULT 0, 
	 CONSTRAINT "PK_MEDECIN" PRIMARY KEY ("NUMEROMED"),
   CONSTRAINT "FK_MEDECIN_SPECIALITE" FOREIGN KEY ("CODESPECIALITE")
	  REFERENCES "SPECIALITE" ("CODESPECIALITE") ENABLE
);

CREATE TABLE "MALADE" 
(	"NUMEROSS" CHAR(15 BYTE) NOT NULL ENABLE, 
	"NOM" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"ADRESSE" CHAR(25 BYTE) NOT NULL ENABLE, 
	"CODEPOSTAL" NUMBER(5,0) NOT NULL ENABLE, 
	"VILLE" CHAR(25 BYTE) NOT NULL ENABLE, 
  CONSTRAINT "PK_MALADE" PRIMARY KEY ("NUMEROSS")
);

CREATE TABLE "TYPEVISITE" 
(	"CODETYPEVISITE" CHAR(25 BYTE) NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(25 BYTE) NOT NULL ENABLE,
  "PRIXVISITE" NUMBER(3,0) DEFAULT 30, 
  CONSTRAINT "PK_TYPEVISITE" PRIMARY KEY ("CODETYPEVISITE")
);

CREATE TABLE "VISITE" 
(	"NUMEROVISITE" CHAR(15 BYTE) NOT NULL ENABLE,
  "NUMEROMED" VARCHAR(12) NOT NULL ENABLE, 
	"NUMEROSS" CHAR(15 BYTE) NOT NULL ENABLE, 
	"DATEVISITE" DATE NOT NULL ENABLE, 
	"CODETYPEVISITE" CHAR(25 BYTE) NOT NULL ENABLE, 
  CONSTRAINT "PK_VISITE" PRIMARY KEY ("NUMEROVISITE"),
  CONSTRAINT "FK_VISITE_MEDECIN" FOREIGN KEY ("NUMEROMED")
	  REFERENCES "MEDECIN" ("NUMEROMED") ENABLE, 
  CONSTRAINT "FK_VISITE_MALADE" FOREIGN KEY ("NUMEROSS")
	  REFERENCES "MALADE" ("NUMEROSS") ENABLE,
  CONSTRAINT "FK_VISITE_TYPEVISITE" FOREIGN KEY ("CODETYPEVISITE")
	  REFERENCES "TYPEVISITE" ("CODETYPEVISITE") ENABLE
);

CREATE TABLE "LOG_LMD" (
  TableName VARCHAR2(32),
  DateEvent Date,
  UserName VARCHAR2(20),
  Action VARCHAR2(25)
);

/****************************************************************************** 
                    TABLE LOG POUR TESTER TRIGGERS
******************************************************************************/

CREATE TABLE "LOG_SYS" (
  UserName VARCHAR2(32),
  EventAction VARCHAR2(20),
  EventDate Date,
  IP_Address VARCHAR2(20),
  InstanceNum VARCHAR2(25)
);